### ISSUE TITLE
Two midis have joined

### ISSUE THREAD

**Issue by joemamamonguschungus** [Kaydax/flp2midi#6] opened 2022-04-10 14:03 UTC
For some reason, the midi file is joined together with the other one

**Comment by Kaydax** [comment] 2022-04-10 14:52
What do you mean? flp2midi does not join midi files together

**Comment by Kaydax** [comment] 2022-04-16 06:21
No explanation on what the actual issue is. Cannot reproduce. Closing

**Closed as completed by Kaydax** 2022-04-16 06:21 UTC
